/**
 * GitHub Actions workflow YAML generator.
 *
 * Security invariants (AC-39/40/41):
 *   - permissions EXACTLY {contents: read, pull-requests: write}
 *   - secret ONLY via ${{ secrets.OPENROUTER_API_KEY }}
 *   - NO pull_request_target trigger
 *   - runner step: `node .devdigest/runner/index.js` (no marketplace action, no npm install)
 */

export interface WorkflowOptions {
  /** pull_request event types to include (e.g. ["opened","synchronize"]). */
  triggers: string[];
  /** How results are posted back to the PR. */
  postAs: "github_review" | "pr_comment" | "none";
}

/**
 * Generate a self-contained `.github/workflows/devdigest-review.yml` string.
 * The caller owns editing (Variant A — edits live in wizard React state).
 */
export function workflowYml({ triggers, postAs }: WorkflowOptions): string {
  const typesList = triggers.map((t) => `      - ${t}`).join("\n");

  return `# DevDigest CI Review — auto-generated by Export Wizard
# ⚠️  The security settings below are required for safe operation.
# ⚠️  Do not add write: to permissions or use pull_request_target.
name: DevDigest Review

on:
  pull_request:
    types:
${typesList}

permissions:
  contents: read
  pull-requests: write

jobs:
  devdigest-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run DevDigest Review
        env:
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          POST_AS: ${postAs}
        run: node .devdigest/runner/index.js

      - name: Upload review results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: devdigest-result
          path: devdigest-result.json
          if-no-files-found: ignore
`;
}
